import express from 'express';
import path from 'path';
import healthRouter from './routes/health';
import { makeLessonsRouter } from './routes/lessons';
import { makeSkillsRouter } from './routes/skills';
import type { AiProvider } from './ai/interface';
import type { AppDatabase } from './db/client';
import { makeAuthRouter } from './auth/routes';
import { makeUsersRouter } from './users/routes';
import { makeLessonSessionsRouter } from './lessonSessions/routes';
import { makeDynamicSessionsRouter } from './sessions/routes';
import { makeDashboardRouter } from './dashboard/routes';
import { makeLearnerRouter } from './learner/routes';
import { makeDiagnosticRouter } from './diagnostic/routes';
import { makeAdminRouter } from './admin/routes';
import { makeFeedbackRouter } from './feedback/routes';

export interface CreateAppOptions {
  db?: AppDatabase;
}

const LOCAL_DEV_ALLOWED_ORIGINS = [
  'http://localhost:3000',
  'http://localhost:8080',
  'http://localhost:57450', // Flutter web dev server
];

/// Public Render-hosted web origins. Hardcoded as a fallback so the
/// shipped frontend can call the backend even when the deploy env
/// has no `PUBLIC_WEB_ORIGIN` / `ALLOWED_ORIGINS` set. The env vars
/// still take precedence — if the user wires either of them, the
/// list below is ignored. Add new public origins here when a new
/// Render web service is provisioned.
const PUBLIC_PROD_ORIGINS = [
  'https://mastery-web-igotsty1e.onrender.com',
];

function getAllowedOrigins(): string[] {
  const explicit = process.env.ALLOWED_ORIGINS
    ?.split(',')
    .map(s => s.trim())
    .filter(Boolean);
  if (explicit?.length) return explicit;

  const publicWebOrigin = process.env.PUBLIC_WEB_ORIGIN?.trim();
  if (publicWebOrigin) {
    return [publicWebOrigin, ...PUBLIC_PROD_ORIGINS, ...LOCAL_DEV_ALLOWED_ORIGINS];
  }
  return [...PUBLIC_PROD_ORIGINS, ...LOCAL_DEV_ALLOWED_ORIGINS];
}

export function createApp(ai: AiProvider, opts: CreateAppOptions = {}): express.Express {
  const allowedOrigins = getAllowedOrigins();
  const app = express();
  app.set('trust proxy', 1);
  app.use((req, res, next) => {
    const origin = req.headers.origin;
    if (origin && allowedOrigins.includes(origin)) {
      res.setHeader('Access-Control-Allow-Origin', origin);
      res.setHeader('Vary', 'Origin');
    }
    res.setHeader('Access-Control-Allow-Methods', 'GET, POST, PATCH, DELETE, OPTIONS');
    res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization');
    if (req.method === 'OPTIONS') { res.sendStatus(204); return; }
    next();
  });
  app.use(express.json());

  // Static audio files for `listening_discrimination` exercises. Files are
  // pre-generated by `npm run gen:audio` (see scripts/gen-audio.ts) and live
  // under backend/public/audio/{lesson_id}/{exercise_id}.mp3. They are
  // content-addressed by hash + voice in the sidecar metadata, so we can
  // safely use a one-year immutable cache.
  app.use(
    '/audio',
    express.static(path.resolve(process.cwd(), 'public', 'audio'), {
      fallthrough: false,
      maxAge: '365d',
      immutable: true,
      setHeaders: res => {
        res.setHeader('Cache-Control', 'public, max-age=31536000, immutable');
      },
    })
  );

  // Static images for the Visual Context Layer (exercise_structure §2.9).
  // Generated offline by `npm run gen:image` and content-addressed by the
  // brief + dont_show + role hash, so the same one-year immutable cache
  // header is safe.
  app.use(
    '/images',
    express.static(path.resolve(process.cwd(), 'public', 'images'), {
      fallthrough: false,
      maxAge: '365d',
      immutable: true,
      setHeaders: res => {
        res.setHeader('Cache-Control', 'public, max-age=31536000, immutable');
      },
    })
  );

  app.use(healthRouter);
  if (opts.db) {
    app.use(makeAuthRouter(opts.db));
    app.use(makeUsersRouter(opts.db));
    app.use(makeLessonSessionsRouter(opts.db, ai));
    app.use(makeDynamicSessionsRouter(opts.db));
    app.use(makeDashboardRouter(opts.db));
    app.use(makeLearnerRouter(opts.db));
    app.use(makeDiagnosticRouter(opts.db));
    app.use(makeAdminRouter(opts.db));
    app.use(makeFeedbackRouter(opts.db));
  }
  app.use(makeLessonsRouter(ai));
  app.use(makeSkillsRouter());

  app.use((_req, res) => {
    res.status(404).json({ error: 'not_found' });
  });

  app.use((err: unknown, _req: express.Request, res: express.Response, _next: express.NextFunction) => {
    console.error(err);
    res.status(500).json({ error: 'internal_error' });
  });

  return app;
}
